_target_: model.encoder.Encoder
vocab_size: 18484 # todo : fix it move into code
hidden_dim: 256
n_layers: 3
n_heads: 8
feedforward_dim: 512
dropout: 0
device: cuda # todo : fix it move into code
max_length: 100